pub use winit::{
    event::KeyEvent,
    keyboard::{
        Key, KeyCode, KeyLocation, ModifiersState, NamedKey, NativeKey, NativeKeyCode, PhysicalKey,
        SmolStr,
    },
};

use {std::ops::Deref, winit::event::DeviceId};

/// An event indicating that
#[derive(Debug, Clone)]
pub struct KeyboardInput {
    /// The ID of the device that was used to generate the event.
    pub device_id: DeviceId,

    /// Indicates that the event has been generated by the windowing system for platform
    /// compatibility.
    ///
    /// When `true`, the OS has not generated this event.
    pub is_synthetic: bool,

    /// The inner event.
    pub inner: KeyEvent,
}

impl Deref for KeyboardInput {
    type Target = KeyEvent;

    #[inline]
    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}
