pub use winit::event::{MouseButton, MouseScrollDelta, TouchPhase};

use {
    vello::kurbo::Point,
    winit::event::{DeviceId, ElementState},
};

/// An event indicating that a mouse button has been pressed or released.
#[derive(Debug, Clone)]
pub struct MouseInput {
    /// The ID of the device that was used to generate the event.
    pub device_id: DeviceId,

    /// Indicates that the event has been generated by the windowing system for platform.
    pub button: MouseButton,

    /// The state of the button.
    pub state: ElementState,
}

/// An event indicating that the mouse has been moved.
#[derive(Debug, Clone)]
pub struct WheelInput {
    /// The ID of the device that was used to generate the event.
    pub device_id: DeviceId,
    /// The amount the mouse wheel was scrolled.
    pub delta: MouseScrollDelta,
    /// The current touch phase.
    pub phase: TouchPhase,
}

/// An event indicating that the mouse has been moved.
#[derive(Debug, Clone)]
pub struct CursorMoved {
    /// The ID of the device that was used to generate the event.
    pub device_id: DeviceId,
    /// The new position of the cursor.
    pub position: Point,
}
