[workspace]
members = ["bins/*", "libs/*"]
default-members = ["bins/yadaw"]
resolver = "2"

[workspace.dependencies]
kui = { path = "libs/kui" }
advice = { path = "libs/advice" }

bitflags = "2"
parking_lot = "0.12"
